/*const morxjest = require('mlar')('morxjest');
const service = require('../services/scaffold/test');*/

/**
 * If you want to run custom tests other than the ones
 * auto generated by morx, you can create a callback
 * with the signature below and run your tests in it
 * @param {*} it - (Alias for Jest's test)
 * @param {*} expect - (Jest's expect)
 * @param {*} q - (Pre-required q object, should in case you wish to do promise related stuff)
 * @param {*} dataArg - (Data passed via morx spec. You can use a different data object)
 *
 */
/*
function callback(it, expect, q, dataArg) {
  it('Should do something', () => {
    const data = dataArg;
    data.allParams.testFee = 900;
    return expect(service(data.allParams)).rejects.toThrow('Service error.');
  });
}
// Runs default morx tests
morxjest.describeThis(service.morxspc, service, { TestName: 'Scaffold thing', IsPromiseMethod: true, timeout: 300000 }, callback);
*/